name: Frontend-CI

on:
    pull_request:
    push:
        branches: ['main', 'master']
concurrency:
    group: frontend-ci-${{ github.ref }}
    cancel-in-progress: true
jobs:
    ci:
        name: Continuous Integration
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./url-shortener-frontend

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'npm'
                  cache-dependency-path: './url-shortener-frontend/package-lock.json'

            - name: Install dependencies
              run: npm ci

            - name: Run ESLint
              run: npm run lint
            - name: Type Check
              run: npm run type-check

            - name: Test Build (Verify Next.js compilation)
              run: npm run build
